### PR TITLE
add description file for samsara-core

### PR DESCRIPTION
**Pull request by puhrez**
addresses  #44

I took the majority of inspiration (and straight docs) from the samsara-core readme and the ingestion-api dockerinfo.md

I'm not very clear on the configurability

### CODE REVIEW

**Comment by BrunoBonacci** [comment]
@puhrez the dockerinfo is incomplete.

The core has a connection to Riemann for metrics tracking and more,
to see volumes and ports exposed see:
https://github.com/samsara/samsara/blob/master/core/Dockerfile

to see which environment variable it takes please see:

  - https://github.com/samsara/samsara/blob/master/core/docker/configure-and-start.sh
  - https://github.com/samsara/samsara/blob/master/core/config/config.edn.tmpl

things like `%%TRACKING_ENABLED||false%%` are placeholder from environment variables which are turned into values at execution time. in this case by passing a `TRACKING_ENABLED` environment variable you can enable or disable tracking. The `||false` is the default value (which need to be mentioned as well.

for more information about how this works see the following library:
https://github.com/BrunoBonacci/synapse

Please add the missing info and resubmit.

**Comment by puhrez** [comment]
@BrunoBonacci thanks for the clarification, I'll add it later today

**Comment by puhrez** [comment]
@BrunoBonacci so I added the things I could understand.
a question:
https://github.com/samsara/samsara/blob/master/core/docker/configure-and-start.sh#L4 says:
```
# REQUIRED: (one or more)
#   KAFKA_PORT_9092_TCP_ADDR
#   ZOOKEEPER_PORT_2181_TCP_ADDR``

however from what I understand by

* https://github.com/samsara/samsara/blob/master/core/config/config.edn.tmpl#L12
* https://github.com/samsara/samsara/blob/master/core/config/config.edn.tmpl#L14
* https://github.com/samsara/samsara/blob/master/core/config/config.edn.tmpl#L21

these and the reinmann stuff are discovered through connected docker containers, thus not configurable options, right? or can environment variables override these discoverable values?

**Comment by BrunoBonacci** [comment]
much better.

  * `OFFSET_RESET`: can be either `:smallest` or `:largest` default `:smallest`
  * kafka, zookeeper and riemann are typically linked container which are resolved automatically when docker is started with `--link`, however if you wish to specify them manually you can do so.
  * kafka and zookeeper links are expected to have more than one instance.

you can put something like

* one or more Zookeeper links are required on client port (2181), for example:
  - `ZOOKEEPER_PORT_2181_TCP_ADDR`, or `ZOOKEEPER1_PORT_2181_TCP_ADDR`, `ZOOKEEPER2_PORT_2181_TCP_ADDR`, and `ZOOKEEPER3_PORT_2181_TCP_ADDR`

same for kafka.

Rieman only one instance is required when the tracking is enabled.

**Pull request merged**
