### PR TITLE
move samsara-core/is-timestamp-reliable to separate module

### PR DESCRIPTION
**Pull request by puhrez**
addresses #29

unable to properly test due to (probably stupid deps issue)
```
λ lein deps
Could not find artifact samsara:moebius:jar:0.5.7.0-SNAPSHOT in clojars (https://clojars.org/repo/)
Could not find artifact samsara:samsara-utils:jar:0.5.7.0-SNAPSHOT in clojars (https://clojars.org/repo/)
This could be due to a typo in :dependencies or network issues.
If you are behind a proxy, try setting the 'http_proxy' environment variable.```

but besides the `:refer :all` i can't think of anything particularly wrong with this

### CODE REVIEW

**Comment by DayoOliyide** [comment]
Hi Puhrez, thanks for the pull request.

To resolve the deps issue , you'll need to run a `lein do clean, install` in both the `moebius` and `utils` directory, to locally install those missing deps.
There's a `build-all-projects.sh` in the bin directory, that does this for all the projects/modules.

@bruno We'll need to add a step to the circleci to add all snapshots, built off master, to clojars **IF**
the entire build is successful. I'll sort this out later today.

**Comment by BrunoBonacci** [comment]
@puhrez I'll try to add some doc on how to set up a local development environment.
@DayoOliyide  see #57 for snapshots build

**Comment by puhrez** [comment]
I ran @DayoOliyide that script (with tests) and every thing seemed cool except this exception

**Comment by puhrez** [comment]
build-all-projects.sh was great, thank you.

**Comment by BrunoBonacci** [comment]
Hi, 

firstly many thanks to send this PR, however I didn't mean just moving the `is-timestamp-reliable` into a new ns. The idea was to create a Samsara's module out of it.

Modules are intended to be pluggable. The current design doesn't allow enough flexibility so I'd rather redesign the modules system first. see #60

I'm sorry, but I can't accept this PR, and it is entirely my fault as I didn't properly document the ticket.

I'm going to put some ideas I have in mind around the design of the new modules system so that if you wish contribute towards that you should have enough information.

**Comment by puhrez** [comment]
@BrunoBonacci ok, please ping me when you have that doc down so I can take a look and see where I can help.

**Pull request closed without merging**
